service: velo-sync-video-processor

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  timeout: 60
  region: ap-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:GetObjectAcl
            - s3:PutObject
            - s3:PutObjectAcl
            - s3:ListObjects
          Resource: '*'

functions:
  app:
    handler: handler.app
    name: velo-sync-video-processor-${sls:stage}

package:
  exclude:
    - .venv/**
    - layer/**
    - test.py
    - requirements.txt